export const SUBMIT_AMOUNT = 'SUBMIT_AMOUNT';
export const SUBMIT_SEATS = 'SUBMIT_SEATS';

export const SELECT_SEAT = 'SELECT_SEAT';
export const UNSELECT_SEAT = 'UNSELECT_SEAT';
export const AUTO_SELECT = 'AUTO_SELECT';

export const REQUEST_SEATS_PENDING = 'REQUEST_SEATS_PENDING';
export const REQUEST_SEATS_SUCCESS = 'REQUEST_SEATS_SUCCESS';
export const REQUEST_SEATS_FAILED = 'REQUEST_SEATS_FAILED';

export const RESERVED_SEATS = 'RESERVED_SEATS';